// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wheuwhxcnnvmktnuwkne.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZXV3aHhjbm52bWt0bnV3a25lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NTkxMjksImV4cCI6MjA2NTUzNTEyOX0.4PZV2B_1HxQmkCdezmh_A401JD_66J_Q4sFl3ZAVsTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);